// SAT Practice Test 7 - Bluebook adaptive route (98 questions)
// Extracted from the user's official MyPractice review on 2026-07-22.
// skill, topic, and difficulty are official per-question values from the College Board Question Bank.

export const SAT2026PT7RWM1Q = {
  1: {
    "passage": "Botanist Al Kovaleski has pointed out that maple trees already thrive in a wide variety of climates and thus may ______ changes in climate better than some other tree species do. The alterations maples may undergo in response to a changing climate are likely to be relatively small and easily achieved.",
    "img": "",
    "question": "Which choice completes the text with the most logical and precise word or phrase?",
    "choice1": "relocate from",
    "choice2": "refer to",
    "choice3": "originate from",
    "choice4": "adapt to",
    "answer": "D"
  },
  2: {
    "passage": "The following text is from John Muir’s 1913 autobiography <i>The Story of My Boyhood and Youth</i>. Muir describes being on a boat.<br><br>The water was so <u>clear</u> that it was almost invisible, and when we floated slowly out over the plants and fishes, we seemed to be miraculously sustained in the air while exploring a veritable fairyland.",
    "img": "",
    "question": "As used in the text, what does the word “<u>clear</u>” most nearly mean?",
    "choice1": "Simple",
    "choice2": "Understandable",
    "choice3": "Obvious",
    "choice4": "Transparent",
    "answer": "D"
  },
  3: {
    "passage": "The recently observed gamma ray burst GRB 230307A lasted for 200 seconds, ______ for a burst generated by the merger of neutron stars. Bursts caused by neutron mergers typically last fewer than 2 seconds.",
    "img": "",
    "question": "Which choice completes the text with the most logical and precise word or phrase?",
    "choice1": "a coincidence",
    "choice2": "a reprieve",
    "choice3": "an incident",
    "choice4": "an oddity",
    "answer": "D"
  },
  4: {
    "passage": "In 1776, the United States sent Benjamin Franklin to France to try to win the country’s support in the United States’ fight for independence from Great Britain. Franklin was very popular in France. This ______ surely helped him to convince France to assist the United States.",
    "img": "",
    "question": "Which choice completes the text with the most logical and precise word or phrase?",
    "choice1": "thoughtfulness",
    "choice2": "esteem",
    "choice3": "controversy",
    "choice4": "sincerity",
    "answer": "B"
  },
  5: {
    "passage": "In the 1950s, scientists didn’t know much about the ocean floor. <u>Many scientists at the time believed that the ocean floor was mostly flat.</u> But geologist Marie Tharp and her research partner, Bruce Heezen, proved that this idea was wrong. Using sonar data collected from the Atlantic Ocean, Tharp and Heezen showed that the floor was filled with canyons, mountains, and valleys.",
    "img": "",
    "question": "Which choice best describes the function of the underlined sentence in the text as a whole?",
    "choice1": "It identifies a scientific belief that Tharp and Heezen showed to be wrong.",
    "choice2": "It describes the design of Tharp and Heezen’s experiment.",
    "choice3": "It emphasizes a disagreement between Tharp and Heezen.",
    "choice4": "It presents data to support a claim that Tharp and Heezen made.",
    "answer": "A"
  },
  6: {
    "passage": "In the early days of television in the 1940s, many people thought that US television programs would rely on the financial support of ad agencies and commercial sponsors, much like radio did. But advertisers hesitated to jump into a new space, <u>particularly at a time when the manufacturing of new television sets was stalled due to the US’s involvement in World War II.</u> Broadcasters, like the National Broadcasting Company (NBC), needed to persuade advertisers to support their programming despite not knowing whether there would be a robust television audience to begin with.",
    "img": "",
    "question": "Which choice best describes the function of the underlined phrase in the text as a whole?",
    "choice1": "It compares the beginnings of radio programming with the beginnings of television programming in the United States.",
    "choice2": "It identifies a specific reason behind some advertisers’ hesitance to support television.",
    "choice3": "It describes how broadcasters attempted to convince advertisers to support television.",
    "choice4": "It explains why a type of television programming was popular at the time.",
    "answer": "B"
  },
  7: {
    "passage": "Pteropods are small swimming snails with thin, delicate calcium carbonate shells. These animals are thought to be especially vulnerable to ocean acidification due to calcium carbonate’s susceptibility to dissolution at lower pH values. Victoria L. Peck and colleagues recently found that the periostracum (a protective coating on pteropods’ outer shells) prevents this dissolution when intact. Moreover, the team was surprised to discover that even when the periostracum is breached, pteropods can still mitigate damage by rebuilding the inner shell wall.",
    "img": "",
    "question": "Which choice best describes the main purpose of the text?",
    "choice1": "To call for additional research on biological mechanisms that improve pteropod survival rates",
    "choice2": "To discuss a conclusion drawn in a study of calcium carbonate’s role in protecting the periostracum of pteropods",
    "choice3": "To address some of the ways ocean acidification has altered pteropod behavior over time",
    "choice4": "To present findings that suggest that a concern about the effects of ocean acidification on pteropod shells may be unwarranted",
    "answer": "D"
  },
  8: {
    "passage": "Text 1<br><br>Little is known about how plate tectonics—wherein slabs of Earth’s crust move over, under, away from, and against one another—began. <u>Some researchers contend</u> that tectonic movements began around 3 billion years ago, often noting that computer models of Earth’s mantle temperature at the time indicate that the mantle would have been sufficiently molten to enable the plates to move.<br><br>Text 2<br><br>Ultimately, any plausible claim about the inception of tectonic movement must rest on empirical evidence from the geological record. Researcher Wriju Chowdhury and his team analyzed the geochemistry of zircon crystals to gain insight into the chemical composition of the magma from which the crystals formed and, based on the data, compellingly argue that plate tectonics may have been occurring as early as 4.2 billion years ago.",
    "img": "",
    "question": "Based on the texts, how would the author of Text 2 most likely respond to what “some researchers contend” as described in Text 1?",
    "choice1": "By suggesting that the temperature of Earth’s mantle 3 billion years ago was likely insufficient to allow for the level of tectonic movement predicted by computer models",
    "choice2": "By distinguishing between computer models of Earth’s mantle temperature that reliably predict the onset of plate tectonics and those that do not",
    "choice3": "By indicating that computer models of Earth’s mantle temperature are still being improved such that new models tend to be much more reliable than their predecessors",
    "choice4": "By asserting that a more definitive form of evidence than the computer models suggests a different timeline for the onset of plate tectonics on Earth",
    "answer": "D"
  },
  9: {
    "passage": "In 2018, scientists discovered an immense aggregation of <i>Muusoctopus robustus</i> (pearl octopuses) along a hydrothermal vent 3,200 meters beneath the ocean’s surface. Water temperatures at this site—named the Octopus Garden—climb as high as 11^{\\circ}C, much warmer than the ambient 1.6^{\\circ}C typical at this depth. Based on observations made over three years, scientists concluded that temperatures at the site likely confer reproductive benefits and that the site is used exclusively for reproduction—6,000 <i>M. robustus</i> adults, hatchlings, and eggs were observed at the garden, but no juveniles were present.",
    "img": "",
    "question": "Which statement about <i>M. robustus</i> and the Octopus Garden is best supported by the text?",
    "choice1": "<i>M. robustus</i> leave the Octopus Garden upon reaching an intermediary stage of development.",
    "choice2": "The <i>M. robustus</i> population at the Octopus Garden remains stable despite variations in water temperature.",
    "choice3": "<i>M. robustus</i> nests in the Octopus Garden contain on average fewer but larger eggs than nests at similar ocean depths.",
    "choice4": "The Octopus Garden provides an ideal feeding ground for <i>M. robustus</i> hatchlings.",
    "answer": "A"
  },
  10: {
    "passage": "Conservationists worldwide are working to protect ecosystems from habitat destruction and biodiversity loss, and in many cases, initiatives that rely on natural features or processes can help address such challenges. In response to a rapidly dwindling population of blueback salmon, the Quinault Indian Nation (a tribe in Washington State) partnered with the conservation organization Wild Salmon Center to restore naturally occurring logjams in the Quinault River. The logjams create shady pools where the blueback salmon can rest and spawn, thus promoting blueback population recovery.",
    "img": "",
    "question": "Which choice best states the main idea of the text?",
    "choice1": "A partnership between the Quinault Indian Nation and Wild Salmon Center shows the importance of collaborative approaches to preserving biodiversity.",
    "choice2": "Nature-based approaches can be effective ways to achieve conservation goals.",
    "choice3": "As indicated by a recent project, logjams help the blueback salmon thrive and reproduce.",
    "choice4": "Scientists now realize that nature-based conservation methods offer better long-term solutions to environmental issues than methods that are not nature-based do.",
    "answer": "B"
  },
  11: {
    "passage": "Alessandro Nai et al. presented study participants with vignettes about fictive political candidates, portraying them as embodying a personality trait widely considered admirable (e.g., agreeableness) or one considered ignoble (e.g., cynicism). A survey recorded participants’ ratings of the candidates’ likability and showed that across participants, ignoble-trait candidates were less likable than admirable-trait candidates. However, when the researchers factored in the participants’ own personality-trait scores, on a scale of 1 (least ignoble) to 7 (most ignoble), they concluded that this relative ranking of candidates persisted except among the participants with high ignobility scores.",
    "img": "sat7-images/sat7-11.svg",
    "question": "Which choice best describes data from the graph that support the researchers’ conclusion?",
    "choice1": "There was a strong positive correlation between participants’ ignobility scores and admirable-trait candidates’ likability ratings, but there was no correlation between ignobility scores and ignoble-trait candidates’ likability ratings.",
    "choice2": "Participants with an ignobility score of 5 or less rated admirable-trait candidates as more likable than ignoble-trait candidates, whereas participants with an ignobility score of 6 or more rated ignoble-trait candidates as equally likable as or even more likable than admirable-trait candidates.",
    "choice3": "Overall, participants rated admirable-trait candidates as quite likable, and that rating was not significantly affected by the participants’ ignobility scores.",
    "choice4": "Unlike participants with an ignobility score of 6, participants with an ignobility score either greater or less than 6 gave admirable-trait candidates and ignoble-trait candidates different likability ratings.",
    "answer": "B"
  },
  12: {
    "passage": "Puerto Rico is an island in the Caribbean Sea. Indigenous people there started raising guinea pigs about 1,700 years ago. Guinea pigs had originally been domesticated much earlier in both Colombia and Peru. So were guinea pigs brought to Puerto Rico from Colombia or from Peru? Ancient Caribbean trade routes connected Puerto Rico with Colombia but not with Peru. <u>Therefore, guinea pigs in Puerto Rico probably came from Colombia and descended from Colombian guinea pigs.</u>",
    "img": "",
    "question": "Which finding, if true, would most directly weaken the underlined claim?",
    "choice1": "Ancient guinea pigs in Puerto Rico were genetically less similar to ancient guinea pigs in Colombia than to ancient guinea pigs in Peru.",
    "choice2": "Guinea pigs are common in ancient Puerto Rican art, especially in pottery.",
    "choice3": "Modern breeds of guinea pigs don’t look like images of guinea pigs in ancient art from Puerto Rico, Colombia, and Peru.",
    "choice4": "The guinea pig population of ancient Colombia was much larger than the guinea pig population of ancient Peru.",
    "answer": "A"
  },
  13: {
    "passage": "“Ad recall” measures how memorable an advertising campaign is. To provide advertisers with information about their ads’ memorability, a social media site regularly surveys users about whether they remember ads they had recently interacted with on the site. In a study that drew on this survey data, advertising researcher Kristen Sussman and colleagues noted that different kinds of social media interactions involve different levels of cognitive engagement: commenting on or sharing a post is more cognitively demanding than is clicking on embedded links or on a “like” button. The researchers hypothesized that interactions indicating high levels of cognitive engagement with ad content would result in relatively high levels of ad recall.",
    "img": "",
    "question": "Which finding, if true, would most directly support the researchers’ hypothesis?",
    "choice1": "Users who interacted with an ad were much more likely to do so by clicking on the ad’s “like” button than they were to interact with the ad in any other way.",
    "choice2": "Users who interacted with an ad were significantly more likely to purchase the advertised product at the time they saw the ad than were users who saw the ad but did not interact with it.",
    "choice3": "Compared with users who clicked on links in an ad, users who commented on that same ad were significantly more likely to remember seeing the ad when surveyed two days later.",
    "choice4": "Although users who shared an ad were highly likely to remember details from the ad when surveyed two days later, those same users tended to forget those details when surveyed again a week later.",
    "answer": "C"
  },
  14: {
    "passage": "A student is researching rotating radio transients (RRATs), a subclass of pulsar stars characterized by short pulses of radio waves. The time between consecutive pulses of an RRAT is referred to as a period. Looking at the table, the student determines that ______",
    "img": "sat7-images/sat7-14.svg",
    "question": "Which choice most effectively uses data from the table to complete the statement?",
    "choice1": "J0614-03 has the shortest amount of time between consecutive pulses of all the RRATs in the table.",
    "choice2": "J0545-03 and J0121+53 have the same amount of time between consecutive pulses.",
    "choice3": "J1654-2335 has the longest amount of time between consecutive pulses of all the RRATs in the table.",
    "choice4": "J0103+54 and J0121+53 both have more than one second of time between consecutive pulses.",
    "answer": "A"
  },
  15: {
    "passage": "Narwhals are shy whales that live in the remote Arctic Ocean. Some of them have a long tusk, like a unicorn horn, with sensitive nerves. Narwhals are known for this tusk, but many actually don’t have one and its purpose is unknown. One group of scientists came up with a possible purpose in 2014. The scientists suggested that the tusk may help narwhals determine when water around them is likely to start freezing and become dangerous for them. Marine biologist Kristin Laidre disagrees with that idea, though. She reasons that if the narwhal’s tusk serves such an important purpose, then it’s most likely that ______",
    "img": "",
    "question": "Which choice most logically completes the text?",
    "choice1": "some narwhals would seek a new habitat.",
    "choice2": "fewer marine animals would also have tusks.",
    "choice3": "more narwhals would have a tusk.",
    "choice4": "narwhals would become less shy over time.",
    "answer": "C"
  },
  16: {
    "passage": "Zydeco music originated in the French Creole community of southwest Louisiana. One instrument that gives zydeco its unique sound is the vest frottoir. The vest frottoir ______ a wearable washboard that is played by rubbing spoons or bottle openers against it.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "have been",
    "choice2": "is",
    "choice3": "were",
    "choice4": "are",
    "answer": "B"
  },
  17: {
    "passage": "Featuring jagged peaks of black ink surrounded by hazy swirls of blue and green paint, Zhang Daqian’s 1983 painting <i>Panorama of Mount Lu</i> is inspired by the tradition of <i>qinglü shanshui</i>, a type of Chinese landscape painting ______ by the use of blue and green hues to depict ethereal, otherworldly landscapes.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "has been characterized",
    "choice2": "will be characterized",
    "choice3": "characterized",
    "choice4": "is characterized",
    "answer": "C"
  },
  18: {
    "passage": "In his <i>Naturalis historia</i>, Pliny the Elder praised Hipparchus’s star catalog, a second-century BCE list of roughly 850 different stars’ celestial positions. For centuries, scholars dreamed about locating a copy of this legendary lost ______ fantasy (partially) became reality in 2022, when researchers uncovered traces of the star catalog on a palimpsest, a reused parchment.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "work, that",
    "choice2": "work that",
    "choice3": "work. That",
    "choice4": "work and that",
    "answer": "C"
  },
  19: {
    "passage": "With a blend of traditional design elements, such as arched Gothic ceilings, and modern ones, such as floor-to-ceiling ______ design splits the difference between old and new, a mixture that is increasingly seen in home interiors in the US.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "windows; transitional",
    "choice2": "windows—transitional",
    "choice3": "windows. Transitional",
    "choice4": "windows, transitional",
    "answer": "D"
  },
  20: {
    "passage": "When a given industry—water and electricity are two well-known examples—carries high infrastructural start-up costs and other barriers that discourage competition, ______ of just one or two suppliers per municipality. Such industries are known as natural monopolies.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "these often consist",
    "choice2": "they often consist",
    "choice3": "it often consists",
    "choice4": "this often consists",
    "answer": "C"
  },
  21: {
    "passage": "Famous for its four-degree tilt, the leaning Garisenda Tower is a popular attraction in Bologna’s city center. However, measurements taken in 2023 showed that the tower was rotating in a concerning way. ______ city officials closed the area around the tower so experts could explore solutions to stabilize the historical twelfth-century structure.",
    "img": "",
    "question": "Which choice completes the text with the most logical transition?",
    "choice1": "Similarly,",
    "choice2": "As a result,",
    "choice3": "For example,",
    "choice4": "In comparison,",
    "answer": "B"
  },
  22: {
    "passage": "Guard cells are specialized cells that are part of a plant’s pores. These cells help regulate the amount of carbon dioxide a plant takes in. ______ they help regulate a plant’s water loss.",
    "img": "",
    "question": "Which choice completes the text with the most logical transition?",
    "choice1": "Additionally,",
    "choice2": "Previously,",
    "choice3": "In conclusion,",
    "choice4": "Instead,",
    "answer": "A"
  },
  23: {
    "passage": "Marcel Duchamp intended his 1917 so-called ready-made sculpture <i>Fountain</i> to challenge then-prevailing conceptions about the nature of art. ______ Duchamp’s Fountain did just that, raising the question of whether displaying any object in an art gallery could be said to transform the object—even, as Duchamp’s sculpture was, a urinal—into a legitimate work of art.",
    "img": "",
    "question": "Which choice completes the text with the most logical transition?",
    "choice1": "Similarly,",
    "choice2": "Indeed,",
    "choice3": "Instead,",
    "choice4": "In addition,",
    "answer": "B"
  },
  24: {
    "passage": "In 2021, a model developed by astrophysicist Catherine Zucker and her research team revealed that the same supernovas responsible for the creation and ongoing expansion of the Local Bubble—a 14-million-year-old cavity in the Milky Way—are likely responsible for the formation of new stars. ______ this model detailed how the bubble’s expansion trapped interstellar clouds of gas and dust that became stars upon their eventual collapse.",
    "img": "",
    "question": "Which choice completes the text with the most logical transition?",
    "choice1": "Hence,",
    "choice2": "However,",
    "choice3": "Admittedly,",
    "choice4": "Specifically,",
    "answer": "D"
  },
  25: {
    "passage": "While researching a topic, a student has taken the following notes: Musicians around the world have used protest songs to raise awareness about human rights violations. US folk singer Aunt Molly Jackson released the protest song “Poor Miner’s Farewell” in 1932. It exposed the unlivable wages and dangerous working conditions coal miners faced in Kentucky during the 1920s and 1930s. South African singer-songwriter Hugh Masekela released the protest song “Bring Him Back Home” in 1987. It called on the South African government to free Nelson Mandela, an anti-apartheid leader who’d been unjustly imprisoned.",
    "img": "",
    "question": "The student wants to contrast the song “Poor Miner’s Farewell” with the song “Bring Him Back Home.” Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    "choice1": "The songs “Poor Miner’s Farewell” and “Bring Him Back Home” both raised awareness about human rights violations.",
    "choice2": "While both are protest songs, “Poor Miner’s Farewell” is about coal miners in Kentucky, whereas “Bring Him Back Home” is about the anti-apartheid leader Nelson Mandela.",
    "choice3": "Hugh Masekela’s song “Bring Him Back Home,” released in 1987, called on the South African government to free Nelson Mandela.",
    "choice4": "Released in 1932 by Aunt Molly Jackson, the song “Poor Miner’s Farewell” was a protest against the unlivable wages and dangerous working conditions faced by Kentucky coal miners.",
    "answer": "B"
  },
  26: {
    "passage": "While researching a topic, a student has taken the following notes: Tibetan mastiffs are large dogs native to the Himalayas. A mutation in their EPAS1 gene prevents excess hemoglobin production. A mutation in their HBB gene boosts hemoglobin’s oxygen-carrying ability. These mutations enable the dogs to withstand hypoxic (low-oxygen) conditions at high altitudes. In a 2016 study, Zhen Wang and colleagues noted that Tibetan wolves’ DNA has the same EPAS1 and HBB mutations. Wang and colleagues determined that the dogs first acquired these mutations by interbreeding with Tibetan wolves around 24,000 years ago.",
    "img": "",
    "question": "The student wants to present the conclusion of Zhen Wang and colleagues’ 2016 study. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    "choice1": "Like Tibetan mastiffs, Tibetan wolves can withstand hypoxic conditions at high altitudes.",
    "choice2": "Both Tibetan mastiffs and Tibetan wolves have mutations in their EPAS1 and HBB genes, which prevent excess hemoglobin production and boost hemoglobin’s oxygen-carrying ability, respectively.",
    "choice3": "In addition to preventing excess hemoglobin production, a mutation in Tibetan mastiffs’ HBB gene boosts hemoglobin’s oxygen-carrying ability.",
    "choice4": "By interbreeding with Tibetan wolves around 24,000 years ago, Tibetan mastiffs acquired the genetic mutations that enable them to withstand hypoxic conditions.",
    "answer": "D"
  },
  27: {
    "passage": "While researching a topic, a student has taken the following notes: Bike-share programs provide bicycles for shared use. In docked bike sharing, riders rent a bike and return it to designated docking stations. Docked programs are orderly and offer consistency to riders but require significant space and money to implement. In dockless bike sharing, riders locate a bike and leave it wherever they choose. Dockless programs are relatively simple and inexpensive to implement and offer flexibility to riders. Dockless programs can be disorganized.",
    "img": "",
    "question": "The student wants to compare some disadvantages of docked and dockless bike-share programs. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    "choice1": "Dockless programs can be disorganized; docked programs, on the other hand, offer order and consistency.",
    "choice2": "Worth noting is that while dockless programs are relatively easy and inexpensive to implement, they are less flexible than docked programs.",
    "choice3": "Docked programs are more resource-intensive than dockless programs, but they avoid some of the latter’s organizational challenges.",
    "choice4": "Though dockless programs offer flexibility, docked bike-share programs provide bicycles for shared use.",
    "answer": "C"
  }
};

export const SAT2026PT7RWM1BD = {
  1: {
    "skill": "Words in Context",
    "topic": "Craft and Structure",
    "difficulty": "Easy"
  },
  2: {
    "skill": "Words in Context",
    "topic": "Craft and Structure",
    "difficulty": "Easy"
  },
  3: {
    "skill": "Words in Context",
    "topic": "Craft and Structure",
    "difficulty": "Medium"
  },
  4: {
    "skill": "Words in Context",
    "topic": "Craft and Structure",
    "difficulty": "Medium"
  },
  5: {
    "skill": "Text Structure and Purpose",
    "topic": "Craft and Structure",
    "difficulty": "Easy"
  },
  6: {
    "skill": "Text Structure and Purpose",
    "topic": "Craft and Structure",
    "difficulty": "Easy"
  },
  7: {
    "skill": "Text Structure and Purpose",
    "topic": "Craft and Structure",
    "difficulty": "Hard"
  },
  8: {
    "skill": "Cross-Text Connections",
    "topic": "Craft and Structure",
    "difficulty": "Medium"
  },
  9: {
    "skill": "Central Ideas and Details",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  10: {
    "skill": "Central Ideas and Details",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  11: {
    "skill": "Command of Evidence",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  12: {
    "skill": "Command of Evidence",
    "topic": "Information and Ideas",
    "difficulty": "Medium"
  },
  13: {
    "skill": "Command of Evidence",
    "topic": "Information and Ideas",
    "difficulty": "Medium"
  },
  14: {
    "skill": "Command of Evidence",
    "topic": "Information and Ideas",
    "difficulty": "Medium"
  },
  15: {
    "skill": "Inferences",
    "topic": "Information and Ideas",
    "difficulty": "Medium"
  },
  16: {
    "skill": "Form, Structure, and Sense",
    "topic": "Standard English Conventions",
    "difficulty": "Easy"
  },
  17: {
    "skill": "Form, Structure, and Sense",
    "topic": "Standard English Conventions",
    "difficulty": "Medium"
  },
  18: {
    "skill": "Boundaries",
    "topic": "Standard English Conventions",
    "difficulty": "Medium"
  },
  19: {
    "skill": "Boundaries",
    "topic": "Standard English Conventions",
    "difficulty": "Hard"
  },
  20: {
    "skill": "Form, Structure, and Sense",
    "topic": "Standard English Conventions",
    "difficulty": "Hard"
  },
  21: {
    "skill": "Transitions",
    "topic": "Expression of Ideas",
    "difficulty": "Easy"
  },
  22: {
    "skill": "Transitions",
    "topic": "Expression of Ideas",
    "difficulty": "Easy"
  },
  23: {
    "skill": "Transitions",
    "topic": "Expression of Ideas",
    "difficulty": "Easy"
  },
  24: {
    "skill": "Transitions",
    "topic": "Expression of Ideas",
    "difficulty": "Medium"
  },
  25: {
    "skill": "Rhetorical Synthesis",
    "topic": "Expression of Ideas",
    "difficulty": "Medium"
  },
  26: {
    "skill": "Rhetorical Synthesis",
    "topic": "Expression of Ideas",
    "difficulty": "Medium"
  },
  27: {
    "skill": "Rhetorical Synthesis",
    "topic": "Expression of Ideas",
    "difficulty": "Hard"
  }
};

export const SAT2026PT7RWM2Q = {
  28: {
    "passage": "At the turn of the twentieth century, Black residents of Richmond, Virginia, had few formal options for banking and other financial services. To ______ this situation, Maggie Lena Walker chartered the St. Luke Penny Savings Bank in 1903. The bank went on to provide home loans and savings opportunities to thousands of Black families over the following decades.",
    "img": "",
    "question": "Which choice completes the text with the most logical and precise word or phrase?",
    "choice1": "prolong",
    "choice2": "rectify",
    "choice3": "retain",
    "choice4": "highlight",
    "answer": "B"
  },
  29: {
    "passage": "The creation of Lotte Reiniger’s 1926 animated film <i>The Adventures of Prince Achmed</i> was ______ process. Over the course of three years, Reiniger and her collaborators painstakingly made more than 250,000 individual images of hand-cut paper silhouettes and repeatedly had to invent entirely new methods and tools to create the special effects Reiniger envisioned.",
    "img": "",
    "question": "Which choice completes the text with the most logical and precise word or phrase?",
    "choice1": "a haphazard",
    "choice2": "a contentious",
    "choice3": "an ineffectual",
    "choice4": "an arduous",
    "answer": "D"
  },
  30: {
    "passage": "Diadromous fish migrate between freshwater and marine biomes during their life cycle. The migration’s obligate nature is why diadromous fish can be ______ those that are merely euryhaline (able to tolerate high salinity): the euryhaline blackchin tilapia can survive high salinity, but its life cycle does not involve relocation to a different biome, as does that of the diadromous wild salmon.",
    "img": "",
    "question": "Which choice completes the text with the most logical and precise word or phrase?",
    "choice1": "demarcated from",
    "choice2": "reconstituted as",
    "choice3": "conflated with",
    "choice4": "derived from",
    "answer": "A"
  },
  31: {
    "passage": "One popular theory of the origin of the Moon, the “big whack,” posits that a protoplanet called Theia collided with Earth, flinging debris into orbit that eventually coalesced into the Moon. Until recently, Theia was ______, but researcher Qian Yuan and colleagues now claim to have identified pieces of the protoplanet in the lowermost section of Earth’s mantle.",
    "img": "",
    "question": "Which choice completes the text with the most logical and precise word or phrase?",
    "choice1": "desultory",
    "choice2": "spurious",
    "choice3": "veritable",
    "choice4": "notional",
    "answer": "D"
  },
  32: {
    "passage": "The following text is from H.D.’s 1916 poem “Mid-Day.” In the poem, the speaker is on a path in an outdoor setting.<br><br><u>A slight wind shakes the seed-pods</u>—<br>my thoughts are spent<br>as the black seeds.<br>My thoughts tear me,<br>I dread their fever.<br>I am scattered in its whirl.<br>I am scattered like<br>the hot shrivelled seeds.",
    "img": "",
    "question": "Which choice best describes the function of the underlined portion in the text as a whole?",
    "choice1": "It illustrates a change in the natural environment that the speaker implies is responsible for the growing misgivings described in the text.",
    "choice2": "It establishes an example of consistency in the natural landscape that the speaker then contrasts with the unpredictability of human emotions.",
    "choice3": "It presents an observation of an occurrence in the natural world that the speaker then expands on to convey a sense of a turbulent interior state.",
    "choice4": "It evokes the ordinariness of an event in nature to suggest that the critical self-evaluation the speaker engages in is a common pursuit.",
    "answer": "C"
  },
  33: {
    "passage": "The Bayeux Tapestry, from eleventh-century France, depicts 75 scenes over 250 feet of fabric. It was likely produced by workers embroidering in sections and then joining the resulting panels together. It’s plausible that the workshop that produced the tapestry had never produced one so large, and some researchers claim that a close examination of the joins—the places where the panels are stitched together—suggests that the workers developed and refined their joining process over the course of production. <u>For example, the first join the workers completed exhibits a clear misalignment of the borders of the two panels, whereas the later joins are virtually invisible.</u>",
    "img": "",
    "question": "Which choice best describes the function of the underlined sentence in the text as a whole?",
    "choice1": "It identifies the people and events depicted in the Bayeux Tapestry.",
    "choice2": "It supports an argument about the workers who produced the Bayeux Tapestry.",
    "choice3": "It compares the Bayeux Tapestry with other tapestries from eleventh-century France.",
    "choice4": "It describes how researchers determined where the Bayeux Tapestry was produced.",
    "answer": "B"
  },
  34: {
    "passage": "The following text is from Thomas Mann’s 1924 novel <i>The Magic Mountain</i>, translated by John E. Woods in 1995.<br><br>The story of Hans Castorp that we intend to tell here—not for <i>his</i> sake (for the reader will come to know him as a perfectly ordinary, if engaging young man), but for the sake of the story itself, which seems to us to be very much worth telling (although in Hans Castorp’s favor it should be noted that it is his story, and that not every story happens to everybody)—is a story that took place long ago, and is, so to speak, covered with the patina of history and must necessarily be told with verbs whose tense is that of the deepest past. ©1995 by Alfred A. Knopf, Inc.",
    "img": "",
    "question": "What does the text most strongly suggest about the story of Hans Castorp?",
    "choice1": "Though it is true that stories of even the most uninteresting people are themselves interesting because all people are unique, the reason this story is interesting is nonetheless difficult to understand because of the passage of time.",
    "choice2": "Even though it is a story of a person of no particular importance, its age and the manner in which it therefore must be told are both indicators that the story itself is important.",
    "choice3": "Like all stories about the lives of inconsequential people, this story must necessarily be related in a particular way if the reason the story is consequential is to be made evident to the audience.",
    "choice4": "It is a remarkable story that happened to an unremarkable person, though one could plausibly argue that because the story is valuable, some of its value accrues to the person at its center.",
    "answer": "D"
  },
  35: {
    "passage": "Early Earth is thought to have been characterized by a stagnant lid tectonic regime, in which the upper lithosphere (the outer rocky layer) was essentially immobile and there was no interaction between the lithosphere and the underlying mantle. Researchers investigated the timing of the transition from a stagnant lid regime to a tectonic plate regime, in which the lithosphere is fractured into dynamic plates that in turn allow lithospheric and mantle material to mix. Examining chemical data from lithospheric and mantle-derived rocks ranging from 285 million to 3.8 billion years old, the researchers dated the transition to 3.2 billion years ago.",
    "img": "",
    "question": "Which finding, if true, would most directly support the researchers’ conclusion?",
    "choice1": "Among rocks known to be older than 3.2 billion years, significantly more are mantle derived than lithospheric, but the opposite is true for the rocks younger than 3.2 billion years.",
    "choice2": "Mantle-derived rocks older than 3.2 billion years show significantly more compositional diversity than lithospheric rocks older than 3.2 billion years do.",
    "choice3": "There is a positive correlation between the age of lithospheric rocks and their chemical similarity to mantle-derived rocks, and that correlation increases significantly in strength at around 3.2 billion years old.",
    "choice4": "Mantle-derived rocks younger than 3.2 billion years contain some material that is not found in older mantle-derived rocks but is found in older and contemporaneous lithospheric rocks.",
    "answer": "D"
  },
  36: {
    "passage": "Almost all works of fiction contain references to the progression of time, including the time of day when events in a story take place. In a 2020 study, Allen Kim, Charuta Pethe, and Steven Skiena claim that an observable pattern in such references reflects a shift in human behavior prompted by the spread of electric lighting in the late nineteenth century. The researchers drew this conclusion from an analysis of more than 50,000 novels spanning many centuries and cultures, using software to recognize and tally both specific time references—that is, clock phrases, such as 7 a.m. or 2:30 p.m.—and implied ones, such as mentions of meals typically associated with a particular time of day.",
    "img": "",
    "question": "Which finding from the study, if true, would most directly support the researchers’ conclusion?",
    "choice1": "Novels published after the year 1800 include the clock phrase 10 a.m. less often than novels published before the year 1800 do.",
    "choice2": "Novels published after 1880 contain significantly more references to activities occurring after 10 p.m. than do novels from earlier periods.",
    "choice3": "Among novels published in the nineteenth century, implied time references become steadily more common than clock phrases as publication dates approach 1900.",
    "choice4": "The time references of noon (12 p.m.) and midnight (12 a.m.) are used with roughly the same frequency in the novels.",
    "answer": "B"
  },
  37: {
    "passage": "In a study of urban physical expansion, Richa Mahtta et al. conducted a meta-analysis of more than 300 cities worldwide to determine whether urban land expansion (ULE) was more strongly influenced by urban population growth or by growth in gross domestic product (GDP) per capita, a measure of economic activity. Because efficient national government is necessary to provide urban services and infrastructure that attract economic investment, Mahtta et al. propose that absent other factors, the importance of GDP per capita growth to ULE would likely increase relative to the importance of population growth as governments become more efficient. If true, this suggests the possibility that ______",
    "img": "sat7-images/sat7-37.svg",
    "question": "Which choice most effectively uses data from the graph to complete the statement?",
    "choice1": "national governments of countries in Region 1 experienced declines in efficiency in the period from 2000 to 2014, relative to the period from 1970 to 2000.",
    "choice2": "countries in Region 1 experienced a slower rate of economic growth in the period from 2000 to 2014 than countries in Region 2 did, despite increasing national government efficiency in Region 1.",
    "choice3": "national governments of most countries in Region 2 became more efficient in the period from 2000 to 2014 than they had been in the period from 1970 to 2000, but those of several countries in this region did not.",
    "choice4": "national governments of countries in Region 1 and in Region 2 generally became more efficient in the period from 2000 to 2014 than they had been in the period from 1970 to 2000, but at different rates.",
    "answer": "A"
  },
  38: {
    "passage": "A student is researching the Chinese government’s 1992 shift to a market economy that emphasizes trade liberalization. One means of trade liberalization involves expanding from ordinary imports into an emphasis on processing imports, which have two types: processing with assembly (in which a firm obtains raw materials from a foreign trading partner without payment and sells the final goods to that partner, charging for assembly) and processing with inputs (in which a firm expends capital to buy raw materials from a trading partner, processes them into final goods, and sells those goods to whichever trading partner it chooses). The student asserts that while initial efforts at trade liberalization were shaped by Chinese firms’ limited capital, this situation resolved during the 2000s.",
    "img": "sat7-images/sat7-38.svg",
    "question": "Which choice best describes data from the graph that support the student’s assertion?",
    "choice1": "Processing imports with inputs were greater than both ordinary imports and processing imports with assembly in 2006.",
    "choice2": "From 2000 to 2006, processing imports with inputs rose much more sharply than processing imports with assembly did.",
    "choice3": "From 2000 to 2006, neither processing imports with inputs nor processing imports with assembly were greater than ordinary imports.",
    "choice4": "Processing imports with assembly were greater in 2006 than processing imports with inputs in 2000.",
    "answer": "B"
  },
  39: {
    "passage": "The Uto-Aztecan language family is divided into a northern branch, which includes the Shoshone language of present-day Idaho and Utah, and a southern one, whose best-known representative is Nahuatl, the language of the Aztec Empire in Mexico. Lexical similarities across the family, including of botanical terms, confirm descent from a single language spoken millennia ago, and the family’s geographical distribution suggests an origin in what is now the US Southwest. However, vocabulary pertaining to maize isn’t shared between northern and southern branches, despite the crop’s universal cultivation among Uto-Aztecan tribes. Given archaeological evidence that maize originated in Mexico and diffused northward into what became the US Southwest, some linguists reason that ______",
    "img": "",
    "question": "Which choice most logically completes the text?",
    "choice1": "northern Uto-Aztecan tribes likely obtained the crop directly from a southern Uto-Aztecan tribe rather than from a non-Uto-Aztecan tribe.",
    "choice2": "variation in maize-related vocabulary within each branch of the Uto-Aztecan family likely reflects regionally specific methods for cultivating the crop.",
    "choice3": "southern Uto-Aztecan tribes likely acquired maize at roughly the same time as northern Uto-Aztecan tribes did, though from different sources.",
    "choice4": "the family’s division into northern and southern branches likely preceded the acquisition of the crop by the Uto-Aztecan tribes.",
    "answer": "D"
  },
  40: {
    "passage": "For its 1974 work <i>Instant Mural</i>, the Chicano art collective Asco taped members Patssi Valdez and Humberto Sandoval to an outdoor wall in East Los Angeles. The work is manifestly a commentary on constraint, but many critics focus on Valdez and the social constraints women faced at the time, which is understandable but leaves the presence of Valdez’s male collaborator Sandoval unexplained. We should instead consider that in 1974, the art establishment’s recognition of Chicano artists was (and had long been) restricted to sociohistorical muralists, leaving nonmuralist Chicano artists—like Asco’s members—struggling to even exhibit their work; attending to this context opens an interpretation that accounts for all the evidence, allowing us to conclude that ______",
    "img": "",
    "question": "Which choice most logically completes the text?",
    "choice1": "while Valdez’s presence in <i>Instant Mural</i> represents the social constraints placed on women at the time, Sandoval’s presence represents Chicano muralists’ frustration at their lack of recognition by the art establishment.",
    "choice2": "the main subject of <i>Instant Mural</i> is female Chicano artists’ experience of being doubly constrained by gender-role expectations and the marginalization of certain types of art.",
    "choice3": "<i>Instant Mural</i> is a reflection on the constraining aesthetic expectations placed on Chicano artists in general rather than on the social constraints placed on women specifically.",
    "choice4": "<i>Instant Mural</i> is best understood not as a critique of the social constraints placed on women but rather as a critique of sociohistorical muralists’ depictions of Chicano culture.",
    "answer": "C"
  },
  41: {
    "passage": "An analysis by Alain Elayi and colleagues of coins minted in Sidon in the fifth and fourth centuries BCE reveals a change in their composition over time: while a coin from circa 450 BCE contains about 98% silver and 1% copper, a coin from 367 BCE (the end of Ba’alšillem II’s reign) contains 74.2% silver and 24.7% copper, giving it a relatively yellowish appearance that traders would have noticed. Because coins with a silver content below 80% were widely considered unsuitable for trade, Elayi et al. speculate that a crisis in confidence in the currency occurred in Sidon around 367 BCE, which was likely relieved—despite Sidon’s persistent oppressive financial obligations—as a result of Ba’alšillem II’s successor Abd’aštart I’s decision to ______",
    "img": "",
    "question": "Which choice most logically completes the text?",
    "choice1": "proclaim that the percentage of silver in coins suitable for trade would be raised to a threshold higher than 80%.",
    "choice2": "keep the amount of silver in Sidonian coins consistent with that in coins minted in 367 BCE but decrease their weight.",
    "choice3": "begin minting heavier coins with a proportion of silver to copper similar to that in coins minted in 367 BCE.",
    "choice4": "fund the mining of some copper deposits that were not available to Ba’alšillem II.",
    "answer": "B"
  },
  42: {
    "passage": "Nigerian American artist Toyin Ojih Odutola uses black-ink pens to create highly detailed drawings of human figures. Her portrait of novelist Zadie ______ is displayed in the National Portrait Gallery in London.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "Smith:",
    "choice2": "Smith—",
    "choice3": "Smith",
    "choice4": "Smith,",
    "answer": "C"
  },
  43: {
    "passage": "A government body officially known as the Althing, ______",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "the world’s oldest parliaments include one which first met in 930 CE, Iceland’s.",
    "choice2": "Iceland’s parliament is one of the oldest in the world, first meeting in 930 CE.",
    "choice3": "the first meeting of one of the oldest parliaments in the world, Iceland’s, was in 930 CE.",
    "choice4": "930 CE was the year when Iceland’s parliament, one of the oldest parliaments in the world, first met.",
    "answer": "B"
  },
  44: {
    "passage": "As the fourteenth US librarian of Congress, Carla Hayden has many responsibilities. These include overseeing the Library of Congress’s collections, which boast more than 162 million ______ the US Copyright Office, which registers copyright claims and advises Congress on copyright law; and appointing the US poet laureate.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "items managing",
    "choice2": "items, managing",
    "choice3": "items; managing",
    "choice4": "items. Managing",
    "answer": "C"
  },
  45: {
    "passage": "Recently unearthed Neronian tools in France dating to 54,000 years ago and attributed to <i>Homo sapiens</i> may provide evidence that interactions between Neanderthals and modern humans occurred 10,000 years earlier than was previously ______ finding that, if true, would overturn current theories about <i>H. sapiens</i> migration during the Upper Paleolithic.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "supposed; a",
    "choice2": "supposed. A",
    "choice3": "supposed a",
    "choice4": "supposed, a",
    "answer": "D"
  },
  46: {
    "passage": "Digital artist Jung (Lulu) Chen primarily uses a suite of software tools to create illustrations for children’s books. To manifest the warm and welcoming atmospheres that are a signature of her ______ she occasionally relies on more traditional art techniques, such as painting with watercolors.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "work, though,",
    "choice2": "work, though",
    "choice3": "work; though,",
    "choice4": "work, though;",
    "answer": "A"
  },
  47: {
    "passage": "Chondrites are stony meteorites that are undifferentiated—that is, their contents have not melted and separated into distinct layers. They are hardly ______ many chondrites experience aqueous alteration as a result of exposure to fluids, as well as fracturing, veining, and localized melting due to collisions with other objects.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "pristine, though",
    "choice2": "pristine, though;",
    "choice3": "pristine; though",
    "choice4": "pristine, though,",
    "answer": "B"
  },
  48: {
    "passage": "That the geographic center of North America lay in the state of North Dakota was conceded by all ______ establishing its precise coordinates proved more divisive.",
    "img": "",
    "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
    "choice1": "involved:",
    "choice2": "involved,",
    "choice3": "involved",
    "choice4": "involved;",
    "answer": "D"
  },
  49: {
    "passage": "Following the American Revolutionary War, North American foodways underwent a radical transformation, fueled in large part by spiking consumer demand for certain grains. The cultivation, trade, and transportation of maize and wheat, ______ reconfigured the continent’s existing regional foodways into a globally oriented food system.",
    "img": "",
    "question": "Which choice completes the text with the most logical transition?",
    "choice1": "in particular,",
    "choice2": "alternatively,",
    "choice3": "by comparison,",
    "choice4": "second of all,",
    "answer": "A"
  },
  50: {
    "passage": "When printing paper money for the colony of Pennsylvania in the 1730s, Benjamin Franklin—then a Philadelphia shop owner—took steps to combat the circulation of counterfeit notes, such as weaving blue threads and muscovite (a reflective mineral) into the paper he used. ______ he stamped the notes with detailed imprints of sage leaves that proved difficult for forgers to replicate.",
    "img": "",
    "question": "Which choice completes the text with the most logical transition?",
    "choice1": "Specifically,",
    "choice2": "That said,",
    "choice3": "For example,",
    "choice4": "Moreover,",
    "answer": "D"
  },
  51: {
    "passage": "While researching a topic, a student has taken the following notes: Angana Chaudhuri is a scientist. Chaudhuri studies sedimentary rocks. A scientist who studies sedimentary rocks is called a sedimentologist. Shale, chalk, and sandstone are examples of sedimentary rocks.",
    "img": "",
    "question": "The student wants to identify what type of scientist Chaudhuri is. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    "choice1": "Chalk is a type of sedimentary rock.",
    "choice2": "Some scientists study shale, chalk, and sandstone.",
    "choice3": "There are scientists who study sedimentary rocks.",
    "choice4": "Chaudhuri is a sedimentologist.",
    "answer": "D"
  },
  52: {
    "passage": "While researching a topic, a student has taken the following notes: Chiura Obata was a Japanese American artist who lived in California. <i>Yosemite Falls</i> is a notable painting by Obata. It uses a Japanese method of black ink painting called sumi-e. This painting was completed in 1930.",
    "img": "",
    "question": "The student wants to indicate the year <i>Yosemite Falls</i> was completed. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    "choice1": "While living in California, Obata created black ink paintings.",
    "choice2": "Obata, a Japanese American artist, created a notable painting.",
    "choice3": "<i>Yosemite Falls</i> was completed in 1930.",
    "choice4": "Obata used a Japanese painting method called sumi-e.",
    "answer": "C"
  },
  53: {
    "passage": "While researching a topic, a student has taken the following notes: Researchers in a 2021 study wanted to determine the rate at which 17 languages conveyed both information and syllables. They calculated the bits of information conveyed per second (the IR, or information rate). The IR was found to be approximately consistent across the 17 languages (an average of 39 bits per second). They calculated the number of syllables spoken per second (the SR, or syllable rate). Spanish had the second-fastest SR (7.7 syllables per second). Vietnamese had the sixteenth-fastest SR (5.3 syllables per second).",
    "img": "",
    "question": "The student wants to present an overview of the study’s findings. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    "choice1": "The 2021 study determined the information rate (IR) of 17 languages in bits of information conveyed per second.",
    "choice2": "Researchers found that information was conveyed more quickly in Spanish, at 7.7 syllables per second, than in Vietnamese, at 5.3 syllables per second.",
    "choice3": "Vietnamese had the sixteenth-fastest syllable rate, lower than that of Spanish, which had the second-fastest; however, Spanish had the lower information rate of the two.",
    "choice4": "Though some of the languages differed in number of syllables spoken per second, all 17 conveyed information at roughly the same rate.",
    "answer": "D"
  },
  54: {
    "passage": "While researching a topic, a student has taken the following notes: The fifth Solvay Conference on Physics was held in 1927. It brought together twenty-nine of the era’s preeminent scientists to discuss the emerging field of quantum theory. The conference famously featured a debate between physicists Albert Einstein and Niels Bohr. Bohr proposed that subatomic entities like electrons had only probable realities until they were observed. Einstein argued that subatomic entities like electrons had a reality independent of observation. Bohr’s position, later called the Copenhagen interpretation, remains the most widely accepted theory of quantum mechanics.",
    "img": "",
    "question": "The student wants to place Einstein’s argument within its historical context. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
    "choice1": "During the dawn of quantum theory, Einstein maintained the independent reality of some subatomic entities, although Bohr’s opposing interpretation would become the widely accepted view.",
    "choice2": "At the 1927 Solvay Conference on Physics, Einstein disagreed with Bohr’s argument that subatomic entities like electrons had a reality independent of observation.",
    "choice3": "The attendees of the 1927 Solvay Conference were among the preeminent scientists of their era, including Einstein, who opposed Bohr’s proposal.",
    "choice4": "In 1927, Einstein and Bohr engaged in a famous debate; Bohr’s argument, later called the Copenhagen interpretation, would remain popular decades after.",
    "answer": "A"
  }
};

export const SAT2026PT7RWM2BD = {
  28: {
    "skill": "Words in Context",
    "topic": "Craft and Structure",
    "difficulty": "Medium"
  },
  29: {
    "skill": "Words in Context",
    "topic": "Craft and Structure",
    "difficulty": "Hard"
  },
  30: {
    "skill": "Words in Context",
    "topic": "Craft and Structure",
    "difficulty": "Hard"
  },
  31: {
    "skill": "Words in Context",
    "topic": "Craft and Structure",
    "difficulty": "Hard"
  },
  32: {
    "skill": "Text Structure and Purpose",
    "topic": "Craft and Structure",
    "difficulty": "Medium"
  },
  33: {
    "skill": "Text Structure and Purpose",
    "topic": "Craft and Structure",
    "difficulty": "Medium"
  },
  34: {
    "skill": "Central Ideas and Details",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  35: {
    "skill": "Command of Evidence",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  36: {
    "skill": "Command of Evidence",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  37: {
    "skill": "Command of Evidence",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  38: {
    "skill": "Command of Evidence",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  39: {
    "skill": "Inferences",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  40: {
    "skill": "Inferences",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  41: {
    "skill": "Inferences",
    "topic": "Information and Ideas",
    "difficulty": "Hard"
  },
  42: {
    "skill": "Boundaries",
    "topic": "Standard English Conventions",
    "difficulty": "Medium"
  },
  43: {
    "skill": "Form, Structure, and Sense",
    "topic": "Standard English Conventions",
    "difficulty": "Hard"
  },
  44: {
    "skill": "Boundaries",
    "topic": "Standard English Conventions",
    "difficulty": "Hard"
  },
  45: {
    "skill": "Boundaries",
    "topic": "Standard English Conventions",
    "difficulty": "Hard"
  },
  46: {
    "skill": "Boundaries",
    "topic": "Standard English Conventions",
    "difficulty": "Hard"
  },
  47: {
    "skill": "Boundaries",
    "topic": "Standard English Conventions",
    "difficulty": "Hard"
  },
  48: {
    "skill": "Boundaries",
    "topic": "Standard English Conventions",
    "difficulty": "Hard"
  },
  49: {
    "skill": "Transitions",
    "topic": "Expression of Ideas",
    "difficulty": "Medium"
  },
  50: {
    "skill": "Transitions",
    "topic": "Expression of Ideas",
    "difficulty": "Hard"
  },
  51: {
    "skill": "Rhetorical Synthesis",
    "topic": "Expression of Ideas",
    "difficulty": "Easy"
  },
  52: {
    "skill": "Rhetorical Synthesis",
    "topic": "Expression of Ideas",
    "difficulty": "Easy"
  },
  53: {
    "skill": "Rhetorical Synthesis",
    "topic": "Expression of Ideas",
    "difficulty": "Hard"
  },
  54: {
    "skill": "Rhetorical Synthesis",
    "topic": "Expression of Ideas",
    "difficulty": "Hard"
  }
};

export const SAT2026PT7MM1Q = {
  55: {
    "img": "",
    "question": "Lorenzo purchased a box of cereal and some strawberries at the grocery store. Lorenzo paid \\($2\\) for the box of cereal and \\($1.90\\) per pound for the strawberries. If Lorenzo paid a total of \\($9.60\\) for the box of cereal and the strawberries, which of the following equations can be used to find \\(p\\), the number of pounds of strawberries Lorenzo purchased? (Assume there is no sales tax.)",
    "choice1": "\\(1.90p + 2 = 9.60\\)",
    "choice2": "\\(1.90p - 2 = 9.60\\)",
    "choice3": "\\(1.90 + 2p = 9.60\\)",
    "choice4": "\\(1.90 - 2p = 9.60\\)",
    "answer": "A"
  },
  56: {
    "img": "",
    "question": "The function \\(f\\) is defined by \\(f(x) = 25x + 30\\). What is the value of \\(f(x)\\) when \\(x = 2\\)?",
    "choice1": "\\(50\\)",
    "choice2": "\\(57\\)",
    "choice3": "\\(80\\)",
    "choice4": "\\(110\\)",
    "answer": "C"
  },
  57: {
    "img": "sat7-images/sat7-57.svg",
    "question": "The graph shown gives the estimated value, in dollars, of a tablet as a function of the number of months since it was purchased. What is the best interpretation of the y-intercept of the graph in this context?",
    "choice1": "The estimated value of the tablet was \\($225\\) when it was purchased.",
    "choice2": "The estimated value of the tablet \\(24\\) months after it was purchased was \\($225\\).",
    "choice3": "The estimated value of the tablet had decreased by \\($225\\) in the \\(24\\) months after it was purchased.",
    "choice4": "The estimated value of the tablet decreased by approximately \\(2.25%\\) each year after it was purchased.",
    "answer": "A"
  },
  58: {
    "img": "",
    "question": "\\(|p| + 61 = 65\\) Which value is a solution to the given equation?",
    "choice1": "\\(\\frac{65}{61}\\)",
    "choice2": "\\(4\\)",
    "choice3": "\\(126\\)",
    "choice4": "\\(130\\)",
    "answer": "B"
  },
  59: {
    "img": "",
    "question": "Triangles \\(EFG\\) and \\(JKL\\) are congruent, where \\(E\\), \\(F\\), and \\(G\\) correspond to \\(J\\), \\(K\\), and \\(L\\), respectively. The measure of angle \\(E\\) is \\(45^{\\circ}\\) and the measure of angle \\(F\\) is \\(20^{\\circ}\\). What is the measure of angle \\(J\\)?",
    "choice1": "\\(20^{\\circ}\\)",
    "choice2": "\\(45^{\\circ}\\)",
    "choice3": "\\(135^{\\circ}\\)",
    "choice4": "\\(160^{\\circ}\\)",
    "answer": "B"
  },
  60: {
    "img": "sat7-images/sat7-60.svg",
    "question": "During the first part of an experiment, a ball was launched from a \\(7\\) -foot-tall platform. The graph shows the height \\(y\\), in feet, of the ball \\(x\\) seconds after it was launched during the first part of the experiment. During the second part of the experiment, the ball was launched the same way, but from a platform that is \\(2\\) feet shorter than the first platform. Which of the following graphs could represent the height \\(y\\), in feet, of the ball \\(x\\) seconds after it was launched during the second part of the experiment?",
    "choice1img": "sat7-images/sat7-60-choice1.svg",
    "choice2img": "sat7-images/sat7-60-choice2.svg",
    "choice3img": "sat7-images/sat7-60-choice3.svg",
    "choice4img": "sat7-images/sat7-60-choice4.svg",
    "answer": "B"
  },
  61: {
    "img": "",
    "question": "The ratio \\(x\\) to \\(y\\) is equivalent to the ratio \\(9\\) to \\(5\\). If the value of \\(x\\) is \\(162\\), what is the value of \\(y\\)?",
    "answer": "90"
  },
  62: {
    "img": "",
    "question": "At a state fair, attendees can win tokens that are worth a different number of points depending on the shape. One attendee won \\(S\\) square tokens and \\(C\\) circle tokens worth a total of \\(1,120\\) points. The equation \\(80S + 90C = 1,120\\) represents this situation. How many more points is a circle token worth than a square token?",
    "choice1": "\\(950\\)",
    "choice2": "\\(90\\)",
    "choice3": "\\(80\\)",
    "choice4": "\\(10\\)",
    "answer": "D"
  },
  63: {
    "img": "",
    "question": "\\(\\frac{(x + 9)(x - 9)}{x + 9} = 7\\) What is the solution to the given equation?",
    "choice1": "\\(7\\)",
    "choice2": "\\(9\\)",
    "choice3": "\\(16\\)",
    "choice4": "\\(63\\)",
    "answer": "C"
  },
  64: {
    "img": "",
    "question": "The equation \\(12t + b = c\\) relates the variables \\(t\\), \\(b\\), and \\(c\\). Which of the following correctly expresses the value of \\(c - b\\) in terms of \\(t\\)?",
    "choice1": "\\(\\frac{t}{12}\\)",
    "choice2": "\\(t\\)",
    "choice3": "\\(t + \\frac{1}{12}\\)",
    "choice4": "\\(12t\\)",
    "answer": "D"
  },
  65: {
    "img": "",
    "question": "What is an x-coordinate of an x-intercept of the graph of \\(y = 3(x - 14)(x + 5)(x + 4)\\) in the <i>xy</i>-plane?",
    "answer": "14"
  },
  66: {
    "img": "",
    "question": "The function f is defined by \\(f(x) = 5(\\frac{1}{4} - x)^{2} + \\frac{11}{4}\\). What is the value of \\(f(\\frac{1}{4})\\)?",
    "answer": "11/4"
  },
  67: {
    "img": "",
    "question": "A circle in the <i>xy</i>-plane has the equation \\((x - 13)^{2} + (y - k)^{2} = 64\\). Which of the following gives the center of the circle and its radius?",
    "choice1": "The center is at \\((13,k)\\) and the radius is \\(8\\).",
    "choice2": "The center is at \\((k,13)\\) and the radius is \\(8\\).",
    "choice3": "The center is at \\((k,13)\\) and the radius is \\(64\\).",
    "choice4": "The center is at \\((13,k)\\) and the radius is \\(64\\).",
    "answer": "A"
  },
  68: {
    "img": "",
    "question": "A circle has a radius of \\(2.1\\) inches. The area of the circle is \\(bπ\\) square inches, where \\(b\\) is a constant. What is the value of \\(b\\)?",
    "answer": "4.41"
  },
  69: {
    "img": "sat7-images/sat7-69.svg",
    "question": "During a study, the temperature, \\(\\text{in}\\text{degrees}\\text{Celsius}(°\\text{C})\\), of the air in a chamber was recorded to the nearest integer at certain times. The scatterplot shows the recorded temperature \\(y\\), \\(\\text{in}°\\text{C}\\), of the air in the chamber \\(x\\) minutes after the start of the study. What was the average rate of change, \\(\\text{in}°\\text{C}\\) per minute, of the recorded temperature of the air in the chamber from \\(x = 5\\) to \\(x = 7\\)?",
    "answer": "5"
  },
  70: {
    "img": "",
    "question": "\\(3y = 4x + 17\\) \\(- 3y = 9x - 23\\) The solution to the given system of equations is \\((x,y)\\). What is the value of \\(39x\\)?",
    "choice1": "\\(- 18\\)",
    "choice2": "\\(- 6\\)",
    "choice3": "\\(6\\)",
    "choice4": "\\(18\\)",
    "answer": "D"
  },
  71: {
    "img": "",
    "question": "The function \\(f(t) = 40,000(2)^{\\frac{t}{790}}\\) gives the number of bacteria in a population \\(t\\) minutes after an initial observation. How much time, in minutes, does it take for the number of bacteria in the population to double?",
    "choice1": "\\(2\\)",
    "choice2": "\\(790\\)",
    "choice3": "\\(1,580\\)",
    "choice4": "\\(40,000\\)",
    "answer": "B"
  },
  72: {
    "img": "",
    "question": "If \\(5 - 7(2 - 4x) = 16 - 8(2 - 4x)\\), what is the value of \\(2 - 4x\\)?",
    "answer": "11"
  },
  73: {
    "img": "",
    "question": "A scientist studying the life cycle of dragonflies counted the number of dragonflies in a certain habitat each day for \\(46\\) days. On February \\(15\\), there were \\(99\\) dragonflies in the habitat. The percent increase in the number of dragonflies in the habitat from January \\(1\\) to February \\(15\\) was \\(12.50%\\). How many dragonflies were in the habitat on January \\(1\\)?",
    "choice1": "\\(88\\)",
    "choice2": "\\(87\\)",
    "choice3": "\\(12\\)",
    "choice4": "\\(8\\)",
    "answer": "A"
  },
  74: {
    "img": "",
    "question": "\\(2x^{2} - 8x - 7 = 0\\) One solution to the given equation can be written as \\(\\frac{8 - \\sqrt{k}}{4}\\), where \\(k\\) is a constant. What is the value of \\(k\\)?",
    "answer": "120"
  },
  75: {
    "img": "",
    "question": "The function \\(f(x)\\) is defined as \\(19\\) more than \\(4\\) times a number \\(x\\). If \\(y = f(x)\\) is graphed in the \\(xy\\) -plane, what is the best interpretation of the \\(x\\) -intercept?",
    "choice1": "When \\(f(x) = 0\\), the number is \\(- \\frac{19}{4}\\).",
    "choice2": "When the number is \\(0\\), \\(f(x) = 19\\).",
    "choice3": "The value of \\(f(x)\\) increases by \\(1\\) for each increase of \\(4\\) in the value of the number.",
    "choice4": "For each increase of \\(1\\) in the value of the number, \\(f(x)\\) increases by \\(4\\).",
    "answer": "A"
  },
  76: {
    "img": "",
    "question": "Which of the following expressions is equivalent to \\((sin24^{\\circ})(cos66^{\\circ}) + (cos24^{\\circ})(sin66^{\\circ})\\)?",
    "choice1": "\\(2(cos66^{\\circ})(sin24^{\\circ})\\)",
    "choice2": "\\(2(cos66^{\\circ}) + 2(cos24^{\\circ})\\)",
    "choice3": "\\((cos66^{\\circ})^{2} + (cos24^{\\circ})^{2}\\)",
    "choice4": "\\((cos66^{\\circ})^{2} + (sin24^{\\circ})^{2}\\)",
    "answer": "C"
  }
};

export const SAT2026PT7MM1BD = {
  55: {
    "skill": "Linear equations in one variable",
    "topic": "Algebra",
    "difficulty": "Easy"
  },
  56: {
    "skill": "Linear functions",
    "topic": "Algebra",
    "difficulty": "Easy"
  },
  57: {
    "skill": "Nonlinear functions",
    "topic": "Advanced Math",
    "difficulty": "Easy"
  },
  58: {
    "skill": "Nonlinear equations in one variable and systems of equations in two variables ",
    "topic": "Advanced Math",
    "difficulty": "Easy"
  },
  59: {
    "skill": "Lines, angles, and triangles",
    "topic": "Geometry and Trigonometry",
    "difficulty": "Easy"
  },
  60: {
    "skill": "Nonlinear functions",
    "topic": "Advanced Math",
    "difficulty": "Easy"
  },
  61: {
    "skill": "Ratios, rates, proportional relationships, and units",
    "topic": "Problem-Solving and Data Analysis",
    "difficulty": "Medium"
  },
  62: {
    "skill": "Linear equations in two variables",
    "topic": "Algebra",
    "difficulty": "Medium"
  },
  63: {
    "skill": "Nonlinear equations in one variable and systems of equations in two variables ",
    "topic": "Advanced Math",
    "difficulty": "Medium"
  },
  64: {
    "skill": "Nonlinear equations in one variable and systems of equations in two variables ",
    "topic": "Advanced Math",
    "difficulty": "Medium"
  },
  65: {
    "skill": "Nonlinear functions",
    "topic": "Advanced Math",
    "difficulty": "Medium"
  },
  66: {
    "skill": "Nonlinear functions",
    "topic": "Advanced Math",
    "difficulty": "Medium"
  },
  67: {
    "skill": "Circles",
    "topic": "Geometry and Trigonometry",
    "difficulty": "Medium"
  },
  68: {
    "skill": "Area and volume",
    "topic": "Geometry and Trigonometry",
    "difficulty": "Medium"
  },
  69: {
    "skill": "Two-variable data: Models and scatterplots",
    "topic": "Problem-Solving and Data Analysis",
    "difficulty": "Medium"
  },
  70: {
    "skill": "Systems of two linear equations in two variables",
    "topic": "Algebra",
    "difficulty": "Medium"
  },
  71: {
    "skill": "Nonlinear functions",
    "topic": "Advanced Math",
    "difficulty": "Medium"
  },
  72: {
    "skill": "Linear equations in one variable",
    "topic": "Algebra",
    "difficulty": "Hard"
  },
  73: {
    "skill": "Percentages",
    "topic": "Problem-Solving and Data Analysis",
    "difficulty": "Hard"
  },
  74: {
    "skill": "Nonlinear equations in one variable and systems of equations in two variables ",
    "topic": "Advanced Math",
    "difficulty": "Hard"
  },
  75: {
    "skill": "Linear functions",
    "topic": "Algebra",
    "difficulty": "Hard"
  },
  76: {
    "skill": "Right triangles and trigonometry",
    "topic": "Geometry and Trigonometry",
    "difficulty": "Hard"
  }
};

export const SAT2026PT7MM2Q = {
  77: {
    "img": "sat7-images/sat7-77.svg",
    "question": "The bar graph summarizes the charge, in kilowatt-hours \\((\\text{kWh})\\), a battery received each day for \\(15\\) days. For how many of these \\(15\\) days did the battery receive a charge of \\(0\\text{kWh}\\)?",
    "choice1": "\\(0\\)",
    "choice2": "\\(1\\)",
    "choice3": "\\(4\\)",
    "choice4": "\\(6\\)",
    "answer": "D"
  },
  78: {
    "img": "sat7-images/sat7-78.svg",
    "question": "In the given scatterplot, a line of best fit for the data is shown.<br><br>Which of the following is closest to the slope of the line of best fit shown?",
    "choice1": "\\(0\\)",
    "choice2": "\\(\\frac{1}{2}\\)",
    "choice3": "\\(1\\)",
    "choice4": "\\(2\\)",
    "answer": "D"
  },
  79: {
    "img": "",
    "question": "In a sample, \\(80%\\) of the items are faulty. There are \\(88\\) faulty items in the sample. How many total items are in the sample?",
    "answer": "110"
  },
  80: {
    "img": "sat7-images/sat7-80.svg",
    "question": "For the exponential function \\(g\\), the table shows four values of \\(x\\) and their corresponding values of \\(g(x)\\). Which equation defines \\(g\\)?",
    "choice1": "\\(g(x) = - 25^{x}\\)",
    "choice2": "\\(g(x) = - (\\frac{1}{25})^{x}\\)",
    "choice3": "\\(g(x) = 25^{x}\\)",
    "choice4": "\\(g(x) = (\\frac{1}{25})^{x}\\)",
    "answer": "D"
  },
  81: {
    "img": "",
    "question": "If \\(8x = 6\\), what is the value of \\(72x\\)?",
    "choice1": "\\(3\\)",
    "choice2": "\\(15\\)",
    "choice3": "\\(54\\)",
    "choice4": "\\(57\\)",
    "answer": "C"
  },
  82: {
    "img": "",
    "question": "Which expression is equivalent to \\(\\frac{h^{15}q^{7}}{h^{5}q^{21}}\\), where \\(h > 0\\) and \\(q > 0\\)?",
    "choice1": "\\(\\frac{h^{10}}{q^{14}}\\)",
    "choice2": "\\(\\frac{h^{3}}{q^{3}}\\)",
    "choice3": "\\(h^{10}q^{14}\\)",
    "choice4": "\\(h^{3}q^{3}\\)",
    "answer": "A"
  },
  83: {
    "img": "",
    "question": "A company fills boxes with approximately \\(23\\) pounds of oranges. To test the accuracy of the filling process, \\(344\\) boxes of oranges were selected at random and weighed. Based on the sample, it is estimated that the average weight of all boxes of oranges filled by the company in an \\(8\\) -hour period is \\(23.1\\) pounds, with an associated margin of error of \\(0.19\\) pounds. Which of the following is the best interpretation of this estimate?",
    "choice1": "Plausible values for the average weight of all boxes of oranges filled by the company are between \\(22.91\\) pounds and \\(23.29\\) pounds.",
    "choice2": "Plausible values for the average weight of all boxes of oranges filled by the company are less than \\(22.91\\) pounds or greater than \\(23.29\\) pounds.",
    "choice3": "The average weight of all boxes of oranges filled by the company is less than \\(23.01\\) pounds.",
    "choice4": "The average weight of all boxes of oranges filled by the company is greater than \\(23.01\\) pounds.",
    "answer": "A"
  },
  84: {
    "img": "",
    "question": "\\(\\frac{1}{3}(x + 6) - \\frac{1}{2}(x + 6) = - 8\\) What value of \\(x\\) is the solution to the given equation?",
    "answer": "42"
  },
  85: {
    "img": "",
    "question": "\\(f(x) = x^{2} + bx\\) \\(g(x) = 9x^{2} - 27x\\) Functions \\(f\\) and \\(g\\) are given, and in function \\(f\\), \\(b\\) is a constant. If \\(f(x)·g(x) = 9x^{4} - 26x^{3} - 3x^{2}\\), what is the value of \\(b\\)?",
    "choice1": "\\(- 26\\)",
    "choice2": "\\(- \\frac{26}{9}\\)",
    "choice3": "\\(\\frac{1}{9}\\)",
    "choice4": "\\(9\\)",
    "answer": "C"
  },
  86: {
    "img": "",
    "question": "In the <i>xy</i>-plane, line \\(s\\) passes through the point \\((0,0)\\) and is parallel to the line represented by the equation \\(y = 18x + 2\\). If line \\(s\\) also passes through the point \\((4,d)\\), what is the value of \\(d\\)?",
    "choice1": "\\(2\\)",
    "choice2": "\\(18\\)",
    "choice3": "\\(72\\)",
    "choice4": "\\(74\\)",
    "answer": "C"
  },
  87: {
    "img": "",
    "question": "\\(f(x) = (x - 44)(x - 46)\\) The function \\(f\\) is defined by the given equation. For what value of \\(x\\) does \\(f(x)\\) reach its minimum?",
    "choice1": "\\(46\\)",
    "choice2": "\\(45\\)",
    "choice3": "\\(44\\)",
    "choice4": "\\(- 1\\)",
    "answer": "B"
  },
  88: {
    "img": "",
    "question": "In triangle \\(XYZ\\), angle \\(Y\\) is a right angle, point \\(P\\) lies on \\(\\overline{XZ}\\), and point \\(Q\\) lies on \\(\\overline{YZ}\\) such that \\(\\overline{PQ}\\) is parallel to \\(\\overline{XY}\\). If the measure of angle \\(XZY\\) is \\(63^{\\circ}\\), what is the measure, in degrees, of angle \\(XPQ\\)?",
    "answer": "153"
  },
  89: {
    "img": "",
    "question": "In a set of four consecutive odd integers, where the integers are ordered from least to greatest, the first integer is represented by \\(x\\). The product of \\(12\\) and the fourth odd integer is at most \\(26\\) less than the sum of the first and third odd integers. Which inequality represents this situation?",
    "choice1": "\\(12(x + 6) \\le x + (x + 4) - 26\\)",
    "choice2": "\\(12(x + 6) \\ge 26 - (x + (x + 4))\\)",
    "choice3": "\\(12(x + 4) \\le x + (x + 3) - 26\\)",
    "choice4": "\\(12(x + 4) \\ge 26 - (x + (x + 3))\\)",
    "answer": "A"
  },
  90: {
    "img": "",
    "question": "\\(\\frac{2}{5}x + \\frac{7}{5}y = \\frac{2}{7}\\) \\(gx + ky = \\frac{5}{2}\\) In the given system of equations, \\(g\\) and \\(k\\) are constants. The system has infinitely many solutions. What is the value of \\(\\frac{g}{k}\\)?",
    "answer": ".2857"
  },
  91: {
    "img": "sat7-images/sat7-91.svg",
    "question": "The table shows three values of \\(x\\) and their corresponding values of \\(y\\), where \\(s\\) is a constant. There is a linear relationship between \\(x\\) and \\(y\\). Which of the following equations represents this relationship?",
    "choice1": "\\(sx + 3y = 18s\\)",
    "choice2": "\\(3x + sy = 18s\\)",
    "choice3": "\\(3x + sy = 18\\)",
    "choice4": "\\(sx + 3y = 18\\)",
    "answer": "B"
  },
  92: {
    "img": "",
    "question": "\\(y + k = x + 26\\) \\(y - k = x^{2} - 5x\\) In the given system of equations, \\(k\\) is a constant. The system has exactly one distinct real solution. What is the value of \\(k\\)?",
    "answer": "17.5"
  },
  93: {
    "img": "",
    "question": "The function \\(f\\) is defined by \\(f(x) = \\frac{1}{2}(x + 6)\\). What is the value of \\(f(4)\\)?",
    "choice1": "\\(20\\)",
    "choice2": "\\(12\\)",
    "choice3": "\\(10\\)",
    "choice4": "\\(5\\)",
    "answer": "D"
  },
  94: {
    "img": "",
    "question": "The area of a rectangular banner is \\(2,661\\) square inches. The banner's length \\(x\\), in inches, is \\(24\\) inches longer than its width, in inches. Which equation represents this situation?",
    "choice1": "\\(0 = x^{2} - 24x - 2,661\\)",
    "choice2": "\\(0 = x^{2} - 24x + 2,661\\)",
    "choice3": "\\(0 = x^{2} + 24x - 2,661\\)",
    "choice4": "\\(0 = x^{2} + 24x + 2,661\\)",
    "answer": "A"
  },
  95: {
    "img": "",
    "question": "A right circular cone has a volume of \\(71,148π\\) cubic centimeters and the area of its base is \\(5,929π\\) square centimeters. What is the slant height, in centimeters, of this cone?",
    "choice1": "\\(12\\)",
    "choice2": "\\(36\\)",
    "choice3": "\\(77\\)",
    "choice4": "\\(85\\)",
    "answer": "D"
  },
  96: {
    "img": "",
    "question": "\\(7x + 6y = 5\\) \\(28x + 24y = 20\\) For each real number \\(r\\), which of the following points lies on the graph of each equation in the <i>xy</i>-plane for the given system?",
    "choice1": "\\((r, - \\frac{6r}{7} + \\frac{5}{7})\\)",
    "choice2": "\\((r,\\frac{7r}{6} + \\frac{5}{6})\\)",
    "choice3": "\\((\\frac{r}{4} + 5, - \\frac{r}{4} + 20)\\)",
    "choice4": "\\(( - \\frac{6r}{7} + \\frac{5}{7},r)\\)",
    "answer": "D"
  },
  97: {
    "img": "",
    "question": "The cost of renting a carpet cleaner is \\($52\\) for the first day and \\($26\\) for each additional day. Which of the following functions gives the cost \\(C(d)\\), in dollars, of renting the carpet cleaner for \\(d\\) days, where \\(d\\) is a positive integer?",
    "choice1": "\\(C(d) = 26d + 26\\)",
    "choice2": "\\(C(d) = 26d + 52\\)",
    "choice3": "\\(C(d) = 52d - 26\\)",
    "choice4": "\\(C(d) = 52d + 78\\)",
    "answer": "A"
  },
  98: {
    "img": "",
    "question": "The speed of a vehicle is increasing at a rate of \\(7.3\\) meters per second squared. What is this rate, in miles per minute squared, rounded to the nearest tenth? \\((\\text{Use}1\\text{mile} = 1,609\\text{meters.})\\)",
    "choice1": "\\(0.3\\)",
    "choice2": "\\(16.3\\)",
    "choice3": "\\(195.8\\)",
    "choice4": "\\(220.4\\)",
    "answer": "B"
  }
};

export const SAT2026PT7MM2BD = {
  77: {
    "skill": "One-variable data: Distributions and measures of center and spread",
    "topic": "Problem-Solving and Data Analysis",
    "difficulty": "Easy"
  },
  78: {
    "skill": "Two-variable data: Models and scatterplots",
    "topic": "Problem-Solving and Data Analysis",
    "difficulty": "Medium"
  },
  79: {
    "skill": "Percentages",
    "topic": "Problem-Solving and Data Analysis",
    "difficulty": "Medium"
  },
  80: {
    "skill": "Nonlinear functions",
    "topic": "Advanced Math",
    "difficulty": "Medium"
  },
  81: {
    "skill": "Linear equations in one variable",
    "topic": "Algebra",
    "difficulty": "Easy"
  },
  82: {
    "skill": "Equivalent expressions",
    "topic": "Advanced Math",
    "difficulty": "Medium"
  },
  83: {
    "skill": "Inference from sample statistics and margin of error ",
    "topic": "Problem-Solving and Data Analysis",
    "difficulty": "Medium"
  },
  84: {
    "skill": "Linear equations in one variable",
    "topic": "Algebra",
    "difficulty": "Medium"
  },
  85: {
    "skill": "Equivalent expressions",
    "topic": "Advanced Math",
    "difficulty": "Medium"
  },
  86: {
    "skill": "Linear equations in two variables",
    "topic": "Algebra",
    "difficulty": "Medium"
  },
  87: {
    "skill": "Nonlinear functions",
    "topic": "Advanced Math",
    "difficulty": "Hard"
  },
  88: {
    "skill": "Lines, angles, and triangles",
    "topic": "Geometry and Trigonometry",
    "difficulty": "Hard"
  },
  89: {
    "skill": "Linear inequalities in one or two variables",
    "topic": "Algebra",
    "difficulty": "Hard"
  },
  90: {
    "skill": "Systems of two linear equations in two variables",
    "topic": "Algebra",
    "difficulty": "Hard"
  },
  91: {
    "skill": "Linear equations in two variables",
    "topic": "Algebra",
    "difficulty": "Hard"
  },
  92: {
    "skill": "Nonlinear equations in one variable and systems of equations in two variables ",
    "topic": "Advanced Math",
    "difficulty": "Hard"
  },
  93: {
    "skill": "Linear functions",
    "topic": "Algebra",
    "difficulty": "Easy"
  },
  94: {
    "skill": "Nonlinear functions",
    "topic": "Advanced Math",
    "difficulty": "Hard"
  },
  95: {
    "skill": "Area and volume",
    "topic": "Geometry and Trigonometry",
    "difficulty": "Hard"
  },
  96: {
    "skill": "Systems of two linear equations in two variables",
    "topic": "Algebra",
    "difficulty": "Hard"
  },
  97: {
    "skill": "Linear functions",
    "topic": "Algebra",
    "difficulty": "Hard"
  },
  98: {
    "skill": "Ratios, rates, proportional relationships, and units",
    "topic": "Problem-Solving and Data Analysis",
    "difficulty": "Hard"
  }
};
